; Global settings for redshift
[redshift]
; Atur temperatur layar (Siang: 5700K agak netral, Malam: 3500K hangat)
temp-day=5700
temp-night=3500

; Transisi halus saat matahari terbenam (1 = Aktif)
transition=1

; Set lokasi ke 'manual' supaya tidak menunggu Geoclue/Internet
location-provider=manual

; Set method ke 'randr' untuk memperbaiki error Wayland di Lubuntu/LXQt
adjustment-method=randr

; Konfigurasi Lokasi (Bali: Latitude negatif, Longitude positif)
[manual]
lat=-8.32
lon=115.19

; Konfigurasi Layar (0 akan menerapkan ke semua monitor yang aktif)
[randr]
screen=0
